introduce feature ast_alloc to toggle ast allocation
cont wip

wip

wip

store span in stub Box

z

add variant ParenthesizedExpression to SimpleAssignmentTarget

Revert "add variant ParenthesizedExpression to SimpleAssignmentTarget"

This reverts commit 9e2a3aed76e41659f9993e7ae87854c3d456732c.

refactor box stub

fix FromInto<Option<..>>

store start in decorator state

Revert "store start in decorator state"

This reverts commit ca89a32b4135b565b50faf01e781c5e7f101fdd5.

fix oxc-parser with ast_alloc disabled

debug ast

fix errors after merge

regenerate & format

enable oxc_ast default features

fix getting &mut span

generate AstVisitBuilder

Use AstVisitBuilder in parser

format

generate scope boundaries in AstVisitBuilder

call enter_scope in parser

make clone_in/from_in generic on Allocator

make CloneIn::Cloned GAT

introduce AstAllocator trait

wip

reset

codegen wip

wip

A

fix macros & serialize

update

update

IntoIn<..., A>

StringLiteral<'a>

fix macros

update

IntoAtom

fix

wip

wip

cloned_in

get_span

wip

cloned_in

CharacterClassContents

derive_where(Debug)

get_span

wip

fix get_span

fix

Z

fix clonein & serde

fix span

To be fixed:

error[E0277]: the trait bound `Option<ast::js::AssignmentTargetMaybeDefault<'a, A>>: GetSpan` is not satisfied
   --> crates/oxc_ast/src/ast/js.rs:911:19
    |
911 |     pub elements: A::Vec<'a, Option<AssignmentTargetMaybeDefault<'a, A>>>,

z

zzz

wip

serialize wip

a

w

handle calls in ast builder

a

z

z

z

a

parser

ast

z

a

fix regex generic allocator

generic regex parser

f

a

wip

grammar z

Revert "grammar z"

This reverts commit 24d1cd5469d78559f8176205cd5d6e9d0c5fe2ca.

parser check passes!

remove ast_alloc feature flag in oxc_parser

fix serialize & lifetime

fix import

fix lifetime

a

wip lifetime wip

fix lifetime in oxc minifier

fix lifetime

fix lifetimes

skip ambient

# Conflicts:
#	crates/oxc_parser/src/cursor.rs
#	crates/oxc_parser/src/js/arrow.rs
#	crates/oxc_parser/src/js/binding.rs
#	crates/oxc_parser/src/js/class.rs
#	crates/oxc_parser/src/js/declaration.rs
#	crates/oxc_parser/src/js/expression.rs
#	crates/oxc_parser/src/js/function.rs
#	crates/oxc_parser/src/js/grammar.rs
#	crates/oxc_parser/src/js/module.rs
#	crates/oxc_parser/src/js/object.rs
#	crates/oxc_parser/src/js/statement.rs
#	crates/oxc_parser/src/jsx/mod.rs
#	crates/oxc_parser/src/lib.rs
#	crates/oxc_parser/src/modifiers.rs
#	crates/oxc_parser/src/ts/statement.rs
#	crates/oxc_parser/src/ts/types.rs

wip

# Conflicts:
#	crates/oxc_parser/src/ts/statement.rs

skip ambient in parse_ts_type

# Conflicts:
#	crates/oxc_parser/src/ts/statement.rs

skip more ambient blocks

# Conflicts:
#	crates/oxc_parser/src/js/class.rs
#	crates/oxc_parser/src/ts/statement.rs

fix test

impl Handler for (), and return handler from parse

handler checkpoint

generate handler call in enum inherit builder

call ast builder when building statement from declaration

format